version: '3.4'

services:
    data_lake:
        build:
          context: .
          dockerfile: data_lake.Dockerfile
        ports:
          - '5433:5433'

    scraper_prod:
        build:
          context: .
          dockerfile: scraper.Dockerfile
          target: scraper_prod
        environment:
          sleep_interval: "60"
          random_order: ""

          # Enables development mode. Leave empty for production
          development: ''
        user: app
        privileged: true
        depends_on:
          - data_lake
        volumes:
          - ./src/extracted_data:/opt/scraper/extracted_data
          - ./logs:/var/log/scraper
