version: '3'

services:
    pgdocker:
        image: postgres
        ports:
          - '5433:5432'
        environment:
          POSTGRES_PASSWORD: 'root'

    scraper-prod:
        build:
          context: .
          dockerfile: scraper.prod.Dockerfile
        image: scraper-prod
        environment:
          sleep_interval: "60"
          random_order: ""
          db_conn_string: "postgresql://postgres:root@pgdocker:5432"

          # Enables development mode. Leave empty for production
          development: ''
        user: apps
        privileged: true
        depends_on:
          - pgdocker
