version: '3'

services:
    webapp_mock:
        build:
            context: WebApp/
            args:
                docker_user: "${DOCKER_USER}"
        ports:
            - 5000:5000
        environment:
            - MOCK=true
        volumes:
            - ../:/home/app/app
        user: $DOCKER_USER
