version: '3'

services:
    data_lake:
        image: postgres:10
        environment:
            - POSTGRES_USER=fee
            - POSTGRES_PASSWORD=dbpassword
            - POSTGRES_DB=data_lake
        ports:
            - 5433:5433
        command: -p 5433
        volumes:
            - data_lake_data:/var/lib/postgresql/data

    daemons:
        build:
            context: ./
            dockerfile: Dockerfile.daemon
            args:
                docker_user: "${DOCKER_USER}"
        depends_on:
            - data_lake
        links:
            - data_lake:data_lake
        volumes:
            - ../:/home/app/app
        user: $DOCKER_USER

volumes:
    data_lake_data:
